# CloudFormationArchitecture/ecr.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repositories for DoggyApp services

Resources:
  FrontendRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: doggyapp/frontend

  OwnerServiceRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: doggyapp/owner-service

  UserServiceRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: doggyapp/user-service

  OrgServiceRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: doggyapp/org-service

Outputs:
  FrontendRepoUri:
    Value: !GetAtt FrontendRepo.RepositoryUri
  OwnerServiceRepoUri:
    Value: !GetAtt OwnerServiceRepo.RepositoryUri
  UserServiceRepoUri:
    Value: !GetAtt UserServiceRepo.RepositoryUri
  OrgServiceRepoUri:
    Value: !GetAtt OrgServiceRepo.RepositoryUri