version: 0.2
env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: admine-user-key-id:key-id
    AWS_SECRET_ACCESS_KEY: admine-user-key-id:secret-key
  variables:
    REGION: "us-east-1"
    TEMPLATE_BUCKET: "doggy-template-build-terminal"
phases:
  install:
    runtime-versions:
      python: 3.9  
    commands:
      - echo "Installing AWS CLI v2..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - aws --version
  build:
    commands:
      - set -e 
      - echo "Packaging CloudFormation template..."
      - aws cloudformation package --template-file master.yaml --s3-bucket $TEMPLATE_BUCKET --output-template-file packaged-root-template.yaml
      - echo "Deploying with secrets injected..."
      - echo "AccessKey= $AWS_ACCESS_KEY_ID"
      - echo "SecretKey= $AWS_SECRET_ACCESS_KEY"
      - if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then echo "Secrets not loaded!"; exit 1; fi
      - |
        aws cloudformation deploy \
          --template-file packaged-root-template.yaml \
          --stack-name my-stack-name \
          --capabilities CAPABILITY_NAMED_IAM \
          --region $REGION \
          --parameter-overrides \
            ParameterKey=AdminAccessKey,ParameterValue=$AWS_ACCESS_KEY_ID \
            ParameterKey=AdminSecretKey,ParameterValue=$AWS_SECRET_ACCESS_KEY


artifacts:
  files:
    - 'packaged-root-template.yaml'