Description: Master stack which creates all required nested stacks

Parameters:
  templatePath: 
    Type: String 
  vpcCidrBlock: 
    Type: String 
  publicSubnet0Cidr: 
    Type: String 
  publicSubnet1Cidr: 
    Type: String 
  privateSubnet0Cidr: 
    Type: String 
  privateSubnet1Cidr: 
    Type: String 
  protectedSubnet0Cidr: 
    Type: String 
  protectedSubnet1Cidr: 
    Type: String
#Tag parameters 
  name: 
    Type: String 
  owner: 
    Type: String
  ownerEmail: 
    Type: String
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
  project: 
    Type: String

Resources:
  VpcStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${templatePath}/vpc.yaml"
      Parameters:
        vpcCidrBlock: !Ref vpcCidrBlock
        publicSubnet0Cidr: !Ref publicSubnet0Cidr
        publicSubnet1Cidr: !Ref publicSubnet1Cidr
        privateSubnet0Cidr: !Ref privateSubnet0Cidr
        privateSubnet1Cidr: !Ref privateSubnet1Cidr
        protectedSubnet0Cidr: !Ref protectedSubnet0Cidr
        protectedSubnet1Cidr: !Ref protectedSubnet1Cidr
        #Tag parameters 
        name: !Ref name
        owner: !Ref owner
        ownerEmail: !Ref ownerEmail
        environment: !Ref environment
        project: !Ref project
      Tags:
        - Key: Name
          Value: VpcStack

