AWSTemplateFormatVersion: "2010-09-09"
Description: Master stack which creates all required nested stacks

Parameters:
  templatePath: 
    Type: String 
    Default: doggy-template-build-terminal
  vpcCidrBlock: 
    Type: String 
    Default: 10.98.0.0/16
  publicSubnet0Cidr: 
    Type: String 
    Default: 10.98.0.0/21
  publicSubnet1Cidr: 
    Type: String 
    Default: 10.98.64.0/21
  privateSubnet0Cidr: 
    Type: String 
    Default: 10.98.16.0/20
  privateSubnet1Cidr: 
    Type: String 
    Default: 10.98.80.0/20
  protectedSubnet0Cidr: 
    Type: String 
    Default: 10.98.8.0/21
  protectedSubnet1Cidr: 
    Type: String
    Default: 10.98.72.0/21

#Tag parameters 
  name: 
    Type: String 
    Default: Ian Martin
  owner: 
    Type: String
    Default: idanzigm
  ownerEmail: 
    Type: String
    Default: idanzigm@gmail.com
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
    Default: production
  project: 
    Type: String
    Default: DoggyApp

Resources:
  VpcStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${templatePath}/vpc.yaml"
      Parameters:
        vpcCidrBlock: !Ref vpcCidrBlock
        publicSubnet0Cidr: !Ref publicSubnet0Cidr
        publicSubnet1Cidr: !Ref publicSubnet1Cidr
        privateSubnet0Cidr: !Ref privateSubnet0Cidr
        privateSubnet1Cidr: !Ref privateSubnet1Cidr
        protectedSubnet0Cidr: !Ref protectedSubnet0Cidr
        protectedSubnet1Cidr: !Ref protectedSubnet1Cidr
        #Tag parameters 
        name: !Ref name
        owner: !Ref owner
        ownerEmail: !Ref ownerEmail
        environment: !Ref environment
        project: !Ref project
      Tags:
        - Key: Name
          Value: VpcStack

  RouteTablesStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${templatePath}/routeTables.yaml"
      Parameters:
        vpc0id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.vpc0id
        igw0id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.igw0id
        publicSubnet0id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.publicSubnet0id
        publicSubnet1id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.publicSubnet1id
        privateSubnet0id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.privateSubnet0id
        privateSubnet1id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.privateSubnet1id
        protectedSubnet0id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.protectedSubnet0id
        protectedSubnet1id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.protectedSubnet1id
        ngw0id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.ngw0id
        ngw1id: 
          Fn::GetAtt: 
          - VpcStack
          - Outputs.ngw1id
        #Tag parameters 
        name: !Ref name
        owner: !Ref owner
        ownerEmail: !Ref ownerEmail
        environment: !Ref environment
        project: !Ref project
      Tags:
        - Key: Name
          Value: RouteTablesStack