AWSTemplateFormatVersion: "2010-09-09"
Description: Creates IAM roles for EKS and mgmt services #for use with mitigated risk of escalation attacks 

Parameters:
  #Tag parameters 
  owner: 
    Type: String
  ownerEmail: 
    Type: String
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
  project: 
    Type: String

Resources: 
  eksClusterRole: 
    Type: AWS::IAM::Role
    Properties: 
      RoleName: eks-cluster-role-dpl
      Description: The role and it's permissions adopted by eks cluster to perform control place funstions neccessary to connect to and manage eks nodes
      AssumeRolePolicyDocument:
         Version: "2012-10-17"
         Statement:
            - Effect: Allow
              Principal:
                Service: eks.amazonaws.com
              Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', role ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 
  
  eksNodeGroupRole: 
    Type: AWS::IAM::Role
    Properties: 
      RoleName: eks-worker-node-service-dpl
      Description: The role and it s permissions adopted by eks worker nodes to perform pod auto scaling and other core functions
      AssumeRolePolicyDocument: 
         Version: "2012-10-17"
         Statement:
            - Effect: Allow
              Principal:
                Service: ec2.amazonaws.com
              Action: sts:AssumeRole
      Policies:
          - PolicyName: ssm-access-to-doggy-nodes  
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Sid: AllowNodeAccess
                  Effect: Allow
                  Action:
                    - ssm:StartSession,
                    - ssm:SendCommand,
                    - ssm:DescribeInstanceInformation
                  Resource: "*"
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', role ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 



Outputs:
  clusterRoleArn: 
    Value: !GetAtt eksClusterRole.Arn

  nodeRoleArn: 
    Value: !GetAtt eksNodeGroupRole.Arn


        
