AWSTemplateFormatVersion: "2010-09-09"
Description: Creates encryption keys for use in EKS folder components 

Parameters:
  name: 
    Type: String 
    Default: Ian Martin
  owner: 
    Type: String
  ownerEmail: 
    Type: String
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
  project: 
    Type: String

Resources: 
  ec2mgmtkey: 
    Type: AWS::KMS::Key
    Properties: 
      Description: Encrypts the volume attached to the ec2 booted with kubctl managing the doggy app EKS cluster 
      Enabled: True
      EnableKeyRotation: True
      KeyPolicy: 
        Version: 2012-10-17
        Statement:  
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: 'arn:aws:109798190983:root'
            Action: 
              - 'kms:*'
            Resource: '*'
          #- Sid: Allows access through EBS for all principals in the account that are authorized 
          #  Effect: Allow
          #  Principal:
          #    AWS: '*'
          #  Action:
          #    - 'kms:DescribeKey'
          #    - 'kms:Encrypt'
          #    - 'kms:Decrypt'
          #    - 'kms:ReEncrypt*'
          #    - 'kms:GenerateDataKey'
          #    - 'kms:CreateGrant'
          #  Resource: '*'
          #  Condition: 
          #    StringEquals: 
          #      kms:ViaService: 'ec2.us-east-1.amazonaws.com'
          #      kms:CallerAccount: '109798190983'
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', key, ec2 ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 

  ec2mgmtkeyalias: 
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: 'alias/ec2mgmtkey-doggyapp'
      TargetKeyId: !Ref ec2mgmtkey

Outputs: 
  ec2KeyId: 
    Value: !Ref ec2mgmtkey


