AWSTemplateFormatVersion: "2010-09-09"
Description: Creates encryption keys for use in EKS folder components 

Parameters:
  mgmtEc2Arn: 
    Type: String
  #tag parameters 
  owner: 
    Type: String
  ownerEmail: 
    Type: String
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
  project: 
    Type: String

Resources: 
  ec2mgmtkey: 
    Type: AWS::KMS::Key
    Properties: 
      Description: Encrypts the volume attached to the ec2 booted with kubctl managing the doggy app EKS cluster. 
      Enabled: True
      EnableKeyRotation: True
      KeyPolicy: 
        Version: 2012-10-17
        Statement:  
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::109798190983:root
            Action: kms:*
            Resource: "*"
          - Sid: Allow use of the key for Admin
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::109798190983:user/admin' 
            Action: 
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: '*'
          - Sid: Allow administration of the key by Admin user 
            Effect: Allow
            Principal: 
              AWS: 'arn:aws:iam::109798190983:user/admin'
            Action: 
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - "kms:TagResource"
              - "kms:UntagResource"
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow attachment of persistent resources 
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::109798190983:user/admin'
            Action:
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
            Resource: '*'
            Condition: 
              Bool: 
                kms:GrantIsForAWSResource: 'true'
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', key, ec2 ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 

  ec2mgmtkeyalias: 
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: 'alias/ec2mgmtkey-doggyapp'
      TargetKeyId: !Ref ec2mgmtkey

Outputs: 
  ec2KeyId: 
    Value: !GetAtt ec2mgmtkey.Arn


