AWSTemplateFormatVersion: "2010-09-09"
Description: Creates IAM roles for EKS and mgmt services 

Parameters:
  eksClusterArn: 
    Type: String
  #Tag parameters 
  owner: 
    Type: String
  ownerEmail: 
    Type: String
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
  project: 
    Type: String

Resources: 

  mgmtInstanceRole: 
    Type: AWS::IAM::Role
    Properties: 
      RoleName: kube-control-base-dpl
      Description: The role and it's permissions adopted by the bastion to issue commands to the kube cluster 
      AssumeRolePolicyDocument: 
         Version: "2012-10-17"
         Statement: 
            - Effect: Allow
              Principal:
                Service: ec2.amazonaws.com
              Action: sts:AssumeRole
      Policies:
          - PolicyName: BastionEKSCustomPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Sid: AllowClusterAccess
                  Effect: Allow
                  Action:
                    - eks:DescribeCluster
                    - sts:GetCallerIdentity
                    - sts:AssumeRole
                  Resource: !Ref eksClusterArn
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # allows the instance to be accessed from SSM so that all ports can remain closed 
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', 'role' ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 

Outputs:

  mgmtInstanceRoleArn: 
    Value: !GetAtt mgmtInstanceRole.Arn

  mgmtInstanceRole: 
    Value: !Ref mgmtInstanceRole

        
