AWSTemplateFormatVersion: "2010-09-09"
Description: Security stack which provides EKS cluster and worker groups with permissions and encryption 

Parameters:
#Stack Parameters 
  vpc0id:
    Type: String
#Tag parameters 
  owner: 
    Type: String
  ownerEmail: 
    Type: String
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
  project: 
    Type: String

Resources:
  clusterSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: EKS cluster security group 
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', EKS-cluster-sg ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 
      VpcId: !Ref vpc0id

  publicNodeSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: EKS node security group 
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', EKS-node-sg ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 
      VpcId: !Ref vpc0id

  managerSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: EC2 manager security group 
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', EC2-manager-sg ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 
      VpcId: !Ref vpc0id

Outputs: 
  clusterSGid: 
    Value: !Ref clusterSecurityGroup

  publicNodeSGid: 
    Value: !Ref publicNodeSecurityGroup

  managerSGid: 
    Value: !Ref managerSecurityGroup