AWSTemplateFormatVersion: "2010-09-09"
Description: EKS stack which creates EKS cluster and worker groups 

Parameters:
#Stack Parameters 
  publicSubnet0id: 
    Type: String 
  publicSubnet1id: 
    Type: String
  privateSubnet0id:
    Type: String
  privateSubnet1id:
    Type: String
  clusterSGid: 
    Type: String 
  managerSGid: 
    Type: String
  clusterRoleArn: 
    Type: String
  nodeRoleArn: 
    Type: String

#Tag parameters. 
  owner: 
    Type: String
  ownerEmail: 
    Type: String
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
  project: 
    Type: String

Resources:
  eksCluster: 
    Type: AWS::EKS::Cluster
    Properties: 
      #Version: 1.28 
      #EncryptionConfig: TODO
      KubernetesNetworkConfig: 
        ServiceIpv4Cidr: 10.100.0.0/16 
      # Logging: 
      #   ClusterLogging: 
      #     EnabledTypes: 
      #       - Type: api
      #       - Type: audit
      #       - Type: authenticator
      #       - Type: controllerManager
      #       - Type: cheduler
      ResourcesVpcConfig: 
        EndpointPrivateAccess: true
        EndpointPublicAccess: false
        #PublicAccessCidrs:
        #  - 0.0.0.0/0 #10.98.0.0/16
        SecurityGroupIds: 
          - !Ref clusterSGid
        SubnetIds: 
          - !Ref privateSubnet0id
          - !Ref privateSubnet1id
      RoleArn: !Ref clusterRoleArn
      Name: doggy-app-eks-cluster-0
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', eks, cluster ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 

  eksNodeGroupPrivate: 
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName: doggy-app-eks-cluster-0
      DiskSize: 20
      # ForceUpdateEnabled: Boolean
      InstanceTypes: 
        - t3.medium
      # Labels: 
      #   Key: Value
      # LaunchTemplate: 
      #   LaunchTemplateSpecification
      NodegroupName: doggy-app-eks-ng-private
      NodeRole: !Ref nodeRoleArn
      # ReleaseVersion: String
      RemoteAccess: 
        Ec2SshKey: doggyApp-mgmt-keyPair
        SourceSecurityGroups: 
          - !Ref managerSGid
      ScalingConfig: 
          DesiredSize: 1
          MaxSize: 2
          MinSize: 1
      Subnets: 
        - !Ref privateSubnet0id
        - !Ref privateSubnet1id
      # Tags: 
      #   Key: Value
      # Taints: 
      #   - Taint
      UpdateConfig: 
        MaxUnavailable: 1
        # MaxUnavailablePercentage: int 1 to 100
      # Version: String
    DependsOn: 
      - eksCluster

Outputs:

  eksClusterArn: 
    Value: !GetAtt eksCluster.Arn