AWSTemplateFormatVersion: "2010-09-09"
Description: EKS stack which creates EKS cluster and worker groups 

Parameters:
#Stack Parameters 
  privateSubnet0id: 
    Type: String 
  privateSubnet1id: 
    Type: String
  clusterSGid: 
    Type: String 
  eksVersion: 
    Type: String
    Default: "1.24"
    AllowedValues: 
      - "1.24"
      - "1.23"
      - "1.22"
      - "1.21"
      - "1.20"
#Tag parameters 
  name: 
    Type: String 
  owner: 
    Type: String
  ownerEmail: 
    Type: String
  environment: 
    Type: String
    AllowedValues: 
      - production
      - development
  project: 
    Type: String

Resources:
  eksCluster: 
    Type: AWS::EKS::Cluster
    Properties: 
      #EncryptionConfig: TODO
      KubernetesNetworkConfig: 
        ServiceIpv4Cidr: 10.100.0.0/16
      #Logging: 
        #TODO
      ResourcesVpcConfig: 
        SecurityGroupIds: 
          - !Ref clusterSGid
        SubnetIds: 
          - !Ref privateSubnet0id
          - !Ref privateSubnet1id
      RoleArn: arn:aws:iam::109798190983:role/EKSclusterRole
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', eks, cluster ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 

  fargateProfile0: 
    Type: AWS::EKS::FargateProfile
    Properties: 
      ClusterName: !Ref eksCluster
      PodExecutionRoleArn: arn:aws:iam::109798190983:role/Fargate-execution
      Selectors: 
        - Namespace: demo-space
      Subnets: 
        - !Ref privateSubnet0id
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', eks, profile0 ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 

  fargateProfile1: 
    Type: AWS::EKS::FargateProfile
    Properties: 
      ClusterName: eksCluster
      PodExecutionRoleArn: arn:aws:iam::109798190983:role/Fargate-execution
      Selectors: 
        - Namespace: demo-space
      Subnets: 
        - !Ref privateSubnet1id
      Tags: 
        - Key: Name 
          Value: !Join ['-', [!Ref 'AWS::StackName', eks, profile1 ]]
        - Key: owner
          Value: !Ref owner
        - Key: OwnerEmail 
          Value: !Ref ownerEmail
        - Key: Environment 
          Value: !Ref environment 
        - Key: project 
          Value: !Ref project 
